#%RAML 0.8

title: SungardAS Private API
baseUri: http://localhost:8081/api/v1
version: 1.0
documentation:
  - title: Private API for CDR
    content: |
      API Manager for Central Data Repository CRUD operations
                         
/customers:
    displayName: Customers
    description: Retrieves a list of customers         
    get:
      queryParameters:
        email:
          description: by email
          type: string
          required: false
        companyName:
          description: by companyName
          type: string
          required: false  
      responses:
        200:
          description: |
            Customers retrieved successfully
          body:
            application/json:
              schema: !include schemas/_dumb-schema.json
              example: !include examples/privateApi/customers-get-example.json                 
                                    
    /{customerId}:
      displayName: getCustomerById
      description: A specific customer (by Id)
      get:
        responses:
          200:
            description: |
              Customer retrieved successfully
            body:
              application/json:
                schema: !include schemas/_dumb-schema.json
                example: !include examples/privateApi/customer-get-example.json
      /addresses:
        displayName: Addresses
        description: Retrieves a list of addresses           
        get: 
          responses:
            200:
              description: |
                Addreses retrieved successfully
              body:
                application/json:
                  schema: !include schemas/_dumb-schema.json
                  example: !include examples/privateApi/addresses-get-example.json
        /{addressId}:
          displayName: getAddressById
          description: A specific address (by Id)
          get:
            responses:
              200:
                description: |
                  Address retrieved successfully
                body:
                  application/json:
                    schema: !include schemas/_dumb-schema.json
                    example: !include examples/privateApi/address-get-example.json                             
      /contacts:
        displayName: Contacts
        description: Retrieves a list of contacts           
        get: 
          responses:
            200:
              description: |
                Contacts retrieved successfully
              body:
                application/json:
                  schema: !include schemas/_dumb-schema.json
                  example: !include examples/privateApi/contacts-get-example.json
        /{contactId}:
          displayName: getContactById
          description: A specific contact (by Id) for a given customer or Sgas employee
          get:
            responses:
              200:
                description: |
                  Contact retrieved successfully
                body:
                  application/json:
                    schema: !include schemas/_dumb-schema.json
                    example: !include examples/privateApi/contact-get-example.json
      /contracts:
        displayName: Contracts
        description: Retrieves a list of contracts           
        get: 
          responses:
            200:
              description: |
                Contracts retrieved successfully
              body:
                application/json:
                  schema: !include schemas/_dumb-schema.json
                  example: !include examples/privateApi/contracts-get-example.json
        /{contractId}:
          displayName: getContractById
          description: A specific contract (by Id)
          get:
            responses:
              200:
                description: |
                  Contract retrieved successfully
                body:
                  application/json:
                    schema: !include schemas/_dumb-schema.json
                    example: !include examples/privateApi/contract-get-example.json
      /billingAccounts:
        displayName: Billing Accounts
        description: Retrieves a list of billing accounts for a given customer           
        get: 
          responses:
            200:
              description: |
                Billing Accounts retrieved successfully
              body:
                application/json:
                  schema: !include schemas/_dumb-schema.json
                  example: !include examples/privateApi/billingAccounts-get-example.json
        /{billingAccountId}:
          displayName: getBillingAccountById
          description: A specific billing account (by Id) for a given customer
          get:
            responses:
              200:
                description: |
                  Billing Account retrieved successfully
                body:
                  application/json:
                    schema: !include schemas/_dumb-schema.json
                    example: !include examples/privateApi/billingAccount-get-example.json  
          /usage:
            displayName: Usage
            description: Retrieves a list of usagess for a given billing account id           
            get: 
              responses:
                200:
                  description: |
                    Usages retrieved successfully
                  body:
                    application/json:
                      schema: !include schemas/_dumb-schema.json
                      example: !include examples/privateApi/usages-get-example.json
                                                 
          /products:
            displayName: Products
            description: Retrieves a list of products for a given billing account           
            get: 
              responses:
                200:
                  description: |
                    Products retrieved successfully
                  body:
                    application/json:
                      schema: !include schemas/_dumb-schema.json
                      example: !include examples/privateApi/products-get-example.json             
            /{productId}:
              displayName: getProductById
              description: A specific product (by Id) for a given billing account
              get:
                responses:
                  200:
                    description: |
                      Product retrieved successfully
                    body:
                      application/json:
                        schema: !include schemas/_dumb-schema.json
                        example: !include examples/privateApi/product-get-example.json              
      /{usageId}:
        displayName: getUsageById
        description: A specific Usage (by Id) for a given customer
        get:
          responses:
            200:
              description: |
                Usage retrieved successfully
              body:
                application/json:
                  schema: !include schemas/_dumb-schema.json
                  example: !include examples/privateApi/usage-get-example.json
                    
/products:
    displayName: Products
    description: Retrieves a list of products         
    get:
      responses:
        200:
          description: |
            Products retrieved successfully
          body:
            application/json:
              schema: !include schemas/_dumb-schema.json
              example: !include examples/privateApi/products-get-example.json                 
                                    
    /{productId}:
      displayName: getProductById
      description: A specific product (by Id)
      get:
        responses:
          200:
            description: |
              Product retrieved successfully
            body:
              application/json:
                schema: !include schemas/_dumb-schema.json
                example: !include examples/privateApi/product-get-example.json
      /rateSheets:
        displayName: Rate Sheets
        description: Retrieves a list of Rate Sheets for a given product         
        get: 
          responses:
            200:
              description: |
                Rate Sheets retrieved successfully
              body:
                application/json:
                  schema: !include schemas/_dumb-schema.json
                  example: !include examples/privateApi/rateSheets-get-example.json
        /{rateSheetId}:
          displayName: getRateSheetById
          description: A specific rateSheet (by Id) for a given product
          get:
            responses:
              200:
                description: |
                  Rate Sheet retrieved successfully
                body:
                  application/json:
                    schema: !include schemas/_dumb-schema.json
                    example: !include examples/privateApi/rateSheet-get-example.json          
      /types:
        displayName: Types
        description: Retrieves a list of types for a given product         
        get: 
          responses:
            200:
              description: |
                Types retrieved successfully
              body:
                application/json:
                  schema: !include schemas/_dumb-schema.json
                  example: !include examples/privateApi/types-get-example.json
        /{typeId}:
          displayName: getTypeById
          description: A specific type (by Id) for a given product
          get:
            responses:
              200:
                description: |
                  Type retrieved successfully
                body:
                  application/json:
                    schema: !include schemas/_dumb-schema.json
                    example: !include examples/privateApi/type-get-example.json      